version: '3.8'

services:
  user-service:
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mj:mjpass@host.docker.internal:5432/mva_user_service  # Connect to local PostgreSQL
      SECRET_KEY: 63d6f576c27dda398024310eb8dd10f9350530c97dbde1568b4976dbc1f6da64
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - ecommerce-network

  kafka:
    image: bitnami/kafka:latest
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - ecommerce-network

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
